### ISSUE TITLE
Adding more  n-gram, extending the list of available languages

### ISSUE THREAD

**Issue by titoBouzout** [FGRibreau/node-language-detect#22]
Hi there!

This has been really useful to me, for quality control. Is accurate and very important: fast. 

I would like to ask for an update of the detected languages. Maybe adding some instructions? or scripts that parse text and extend the database?

Many thanks

**Comment by tommedema** [comment]
Is Chinese (simplified) supported?

**Comment by RuslanZavacky** [comment]
https://github.com/wooorm/franc is a library which supports more languages, I suggest to have a look.
