### ISSUE TITLE
Option to return language as iso2 or iso3

### ISSUE THREAD

**Issue by ajmas** [FGRibreau/node-language-detect#31]
Would it be possible to add an optional third parameter to `LanguageDetect.detect()` that would allow add a property to return the languages as iso2 or iso3. If it is already possible, could this be added to the docs?

Example:

```
LanguageDetect.detect(text, 1, { langType: 'iso2' } )
```

**Comment by ajmas** [comment]
Digging into the code a bit I see that `setLanguageType()` is available, but not exposed to Typescript. Will add a PR if it is welcome.

**Comment by ajmas** [comment]
PR: https://github.com/FGRibreau/node-language-detect/pull/32

**Comment by FGRibreau** [comment]
Merged :+1: thanks!
