### ISSUE TITLE
Source of language datasets

### ISSUE THREAD

**Issue by DonaldTsang** [FGRibreau/node-language-detect#37]
Where is the source text dataset for the Ngrams of those 52 languages? Would like to see if it is different from https://github.com/wooorm/franc/issues/78 usage of UDHR, and if it is more accurate than them.

**Comment by mahnunchik** [comment]
Ping @FGRibreau

**Comment by FGRibreau** [comment]
As said in the README, the whole database came fromhttps://pear.php.net/package/Text_LanguageDetect
