### ISSUE TITLE
English text is detecting as Danish

### ISSUE THREAD

**Issue by parweennargis** [FGRibreau/node-language-detect#42]
I am using the npm module languagedetect (version: ^2.0.0).
For simple English string, it is returning the language as danish with the highest score and English with less score.
`const text = 'Test from backend';
const languages = lngDetector.detect(text, 2);`

The response which I am getting in `languages` is:
`[["danish",0.2868627450980392],["english",0.2733333333333333]]`

**Comment by FGRibreau** [comment]
see https://github.com/FGRibreau/node-language-detect/issues/41#issuecomment-1003045188 :)
